#! /bin/sh
echo building: convert shaders...
node utils/glslLoader.js || exit 1
echo building: format codes...
tsfmt **/*.ts -r
echo building: compile codes...
tsc || exit 1
echo building: uglifying...
uglifyjs build/release/canvas-toy.js -o build/release/canvas-toy-min.js
echo building: build examples...
cd examples
tsc || exit 1
echo 'building: done.'
