#! /bin/sh
echo building: convert shaders...
node utils/glslLoader.js
echo building: format codes...
tsfmt **/*.ts -r
echo building: compile codes...
tsc
echo building: uglifying...
uglifyjs build/release/canvas-toy.js -o build/release/canvas-toy-min.js
echo 'building: done.'
